# see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package to npmjs for GPA

on:
  # push:
  #   tags:
  #     - 'v*'
  release:
    types: [created]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          # registry-url: https://registry.npmjs.com
          # cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Release
        run: npm run release-version

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./docs

      - name: npm-publish
        run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
